#!/usr/bin/env python3
import sys
import shlex
import re
def main():
	filename = sys.argv[1]
	report_error = 1 if(len(sys.argv) != 3) else int(sys.argv[2])
	b = list()
	with open(filename) as f:
		s = shlex.shlex(f, posix=True)
		s.whitespace_split = True
		b.append('/* Automatically generated from {} by {} */'.format(sys.argv[1], sys.argv[0][2:]))
		b.append('/* Do not edit this file! */')
		b.append('#ifndef {}_H'.format(sys.argv[0][2:-3].upper()))
		b.append('#define {}_H'.format(sys.argv[0][2:-3].upper()))
		while True:
			token = s.get_token()
			if(token == None):
				break
			if(token == '/*'):
				while(token != '*/'):
					token = s.get_token()
				continue
			if(token == 'struct'):
				wr_mask = 0
				rd_mask = 0
				ident = s.get_token()[:-2]
				token = s.get_token()
				if(token == '{'):
					while(token != '};'):
						token = s.get_token()
						if(token == 'ATTRIBUTE_NONE'):
							s.get_token()
							continue
						elif(token == 'ATTRIBUTE_RDONLY'):
							token = s.get_token()
							m = re.search('\[\d+\]', token)
							n = int(m.group()[1:-1])
							rd_mask = (rd_mask << n) | (0xffffffff>>(32-n))
							wr_mask = (wr_mask << n) | (0x00000000>>(32-n))
						elif(token == 'ATTRIBUTE_WIRI'):
							token = s.get_token()
							m = re.search('\[\d+\]', token)
							n = int(m.group()[1:-1])
							rd_mask = (rd_mask << n) | (0xffffffff>>(32-n))
							wr_mask = (wr_mask << n) | (0x00000000>>(32-n))
						elif(token == 'ATTRIBUTE_WPRI'):
							token = s.get_token()
							m = re.search('\[\d+\]', token)
							n = int(m.group()[1:-1])
							rd_mask = (rd_mask << n) | (0xffffffff>>(32-n))
							wr_mask = (wr_mask << n) | (0x00000000>>(32-n))
						elif(token == 'ATTRIBUTE_WLRL'):
							token = s.get_token()
							m = re.search('\[\d+\]', token)
							n = int(m.group()[1:-1])
							rd_mask = (rd_mask << n) | (0xffffffff>>(32-n))
							wr_mask = (wr_mask << n) | (0xffffffff>>(32-n))
						elif(token == 'ATTRIBUTE_WARL'):
							token = s.get_token()
							m = re.search('\[\d+\]', token)
							n = int(m.group()[1:-1])
							rd_mask = (rd_mask << n) | (0xffffffff>>(32-n))
							wr_mask = (wr_mask << n) | (0xffffffff>>(32-n))
						elif(token != '};'):
							if(report_error):
								print('Error(line:{}): No attribute near {}'.format(s.lineno-1, token))
								sys.exit(1)
				b.append('#define\t{}_WR_MASK\t32\'b{:0=32b}'.format(ident.upper(), (wr_mask)))
				b.append('#define\t{}_RD_MASK\t32\'b{:0=32b}'.format(ident.upper(), (rd_mask)))
		b.append('#endif')
		for c in b:
			print(c)
if __name__ == '__main__':
	main()
